stages:
  # - make_assets
  # - embed_reveal
  - docusaurus

build_dir: /build
output_type: last
output_dir: /output

make_assets:
  plugin: command
  options:
    command: make
    locations:
      # - chapters/introduction/lecture
      # - chapters/protocol/lecture
      # - chapters/case-study/lecture/slides
      # - chapters/wallet/lecture/slides
      # - chapters/vm/lecture
      # - chapters/smart-contracts/lecture
      # - chapters/security/lecture
      # - chapters/dApps/lecture
      # - chapters/composability/lecture
    args:
      - all

# embed_reveal:
#   plugin: reveal_embed
#   options:
#     target: docusaurus
#     extension: mdx
#     build:
      # Introduction: slides/Introduction
      # Protocol: slides/protocol
      # Case-Study: slides/case-study
      # Wallet: slides/wallet
      # VM: slides/vm
      # Smart-Contracts: slides/smart-contracts
      # Security: slides/security
      # Dapps: slides/dApps
      # Composability: slides/composability

docusaurus:
  plugin: docusaurus
  options:
    course_name: Blockchain Protocols and Distributed Applications
    sidebar: js
    structure:
      - Introduction: chapters/README.md
      - Lectures:
          - Introduction: chapters/introduction/lecture/Introduction.mdx
          # - Blockchain Protocols: chapters/protocol/lecture/slides/protocol.md
          # - Smart Contracts: chapters/smart-contracts/lecture/slides/smart-contracts.md
          # - Security: chapters/security/lecture/slides/security.md
          # - dApps: chapters/dApps/lecture/slides/dApps.md
          # - Composability: chapters/composability/lecture/slides/composability.md
      - Practical Sessions:
          - Environment Setup: chapters/introduction/lab/content/setup/setup.md
          # - Wallet Operations: chapters/introduction/lab/content/wallet/wallet.md
          # - Blockchain Explorer: chapters/introduction/lab/content/explorer/blocks.md
          # - Smart Contracts: chapters/smart-contracts/lab/content/adder.md
          # - Tokens: chapters/tokens/lab/content/fungible.md
          # - dApps: chapters/dApps/lab/content/dApp.md
      - Assignments:
          # - Assignment 1: assignments/assignment1.md
          # - Assignment 2: assignments/assignment2.md
          # - Project: assignments/project.md
          # - Blockchain Research Assignment: assignments/blockchain_research_assignment.md
          # - Scientific Research Assignment: assignments/scientific_research_assignment.md
      # - Grading: util/grading.md
      - Getting Started: utils/getting_started.md
      - Resources: util/resources.md
    # static_assets:
    #   - slides/Compute: /build/make_assets/content/chapters/introduction/lecture/_site
    config_meta:
      title: Blockchain Summer School 2025
      url: https://cs-pub-ro.github.io/
      baseUrl: /blockchain-summer-school/
      onBrokenLinks: warn
      onBrokenMarkdownLinks: warn
    copyright_string: © 2025 University POLITEHNICA of Bucharest.
